# [defaults](https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml)
# [documentation](https://yazi-rs.github.io/docs/configuration/keymap)

[mgr]
prepend_keymap = [
	{ on = "l", run = "plugin smart-enter", desc = "Enter dir or open file" },
	{ on = "<Enter>", run = "plugin smart-enter", desc = "Enter dir or open file" },
	{ on = "P", run = "plugin toggle-pane min-preview", desc = "Show/Hide preview" },
	{ on = "T", run = "plugin toggle-pane min-parent", desc = "Show/Hide parent" },
]
